apiVersion: v1
kind: Service
metadata:
  name: sts-nginx-headless
  labels:
    applabel: nginx
spec:
  ports:
  - port: 80
    name: web
  clusterIP: None
  selector:
    applabel: nginx
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: web
spec:
  selector:
    matchLabels:
      applabel: nginx # has to match .spec.template.metadata.labels
  serviceName: "sts-nginx-headless"
  replicas: 3 # by default is 1
  template:
    metadata:
      labels:
        applabel: nginx # has to match .spec.selector.matchLabels
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80
          name: web