kind: HorizontalPodAutoscaler
apiVersion: autoscaling/v2beta2
metadata:
  name: image-transcoder-hpa
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: StatefulSet
    name: image-transcoder
  minReplicas: 1
  maxReplicas: 20
  metrics:
    - type: Object
      object:
        metric:
          name: kafka_image_queue_lag
        describedObject:
          kind: Namespace
          name: default
        target:
          type: Value
          value: 500
